alias: Warmwasser Morgens aufheizen
description: >-
  Warmwasserbereitung 30 Minuten vor Beginn der Heizperiode nach
  Kalendereintrag. Dazu musse einen lokalen Kalender "Heizung" mit dem
  Kalendereintrag "Heizen" geben, welcher dem in der Buderusheizung
  eingestelltem Heizplan entspricht.
trigger:
  - platform: calendar
    event: start
    entity_id: calendar.heizung
    offset: "0:30:0"
condition:
  - condition: template
    value_template: "{{ 'Heizen' in trigger.calendar_event.summary }}"
action:
  - service: number.set_value
    data:
      value: >-
        {{ ([55.0, (10.5-(states('sensor.gedaempfte_aussentemperatur') |
        float))*2+45, 45.0]|sort)[1] }}
    target:
      entity_id: number.warmwassersolltemperatur_tag
    enabled: true
  - service: number.set_value
    data:
      value: 48
    target:
      entity_id: number.warmwassersolltemperatur_tag
    enabled: false
  - service: automation.trigger
    data: {}
    target:
      entity_id: automation.ww_push
mode: single
