# Read and write entities only needed if hc2 aka Heizkreis2 is present in your system
# For that Module FM241 should be installed https://the78mole.de/wp-content/uploads/2021/07/67903492.pdf
substitutions:
  name: "km271-for-friends"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  platformio_options:
    upload_speed: 921600
    #board_build.f_flash: 80000000L
    #board_build.partitions: "default_8MB.csv
    #upload_flash_size: "8MB"

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: the78mole.km271-wifi
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
#  password: "xxx"

wifi:
#  ssid: "test"
#  password: "testtest"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "Z8zfajgxVvNw"

dashboard_import:
  package_import_url: github://the78mole/esphome_components/components/km271_wifi/km271-for-friends.yaml@main

captive_portal:
#  keep_user_credentials: true

uart:
  id: uart_bus
  tx_pin: GPIO2
  rx_pin: GPIO4
  baud_rate: 2400

external_components:
#  - source:
#      type: local
#      path: my_components/components
#    components: [ km271_wifi ]
  - source: github://the78mole/esphome_components@main
    components: [ km271_wifi ]
 
esp32_improv:
  authorizer: improvble
  authorized_duration: 120s
  status_indicator: led3
  identify_duration: 60s

improv_serial: 
    
status_led:
  id: ledgn1
  pin: 
    number: GPIO21
    inverted: true

km271_wifi:
  - id: budoil
    uart_id: uart_bus

select:
  - platform: km271_wifi
    config_heating_circuit_2_summer_winter_switch_temperature:
      name: "HK2 Sommer Winter Umschalttemperatur"
    config_heating_circuit_2_operation_mode:
      name: "HK2 Betriebsmodus"
    config_heating_circuit_2_lowering_type:
      name: "HK2 Absenkungsart"
    config_heating_circuit_2_heating_system_type:
      name: "HK2 Heizsystem"
    config_heating_circuit_2_heating_program:
      name: "HK2 Heizprogramm"

number:
  - platform: km271_wifi
    config_heating_circuit_2_room_target_temperature_night:
      name: "HK2 Raumsolltemperatur Nacht"
      unit_of_measurement: "°C"
      device_class: temperature
    config_heating_circuit_2_room_target_temperature_day:
      name: "HK2 Raumsolltemperatur Tag"
      unit_of_measurement: "°C"
      device_class: temperature
    config_heating_circuit_2_holiday_target_temperature:
      name: "Urlaubstemperatur"
      unit_of_measurement: "°C"
      device_class: temperature
    config_heating_circuit_2_flow_temperature_max:
      name: "HK2 Heizkreistemperatur Maximal"
      unit_of_measurement: "°C"
      device_class: temperature
    config_heating_circuit_2_design_temperature:
      name: "HK2 Auslegungstemperatur"
      unit_of_measurement: "°C"
      device_class: temperature
#     handled by config_frost_switch_temperature
#    config_heating_circuit_2_outdoor_switch_temperature:
#      unit_of_measurement: "°C"
#      device_class: temperature
#      name: "HK2 Aussenhalt Umschalttemperatur"
    config_heating_circuit_2_room_temperature_offset:
      name: "HK2 Raumtemperatur Offset"
      unit_of_measurement: "°C"
      device_class: temperature
    config_heating_circuit_2_holiday_days:
      name: "HK2 Urlaubstage"

output:
  - platform: gpio
    id: led3
    #name: LED3_Yellow
    pin: 
      number: 23
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: led4
    #name: LED4_Red
    pin: 
      number: 25
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
    id: improvble
    name: "USER 2"
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: km271_wifi
    # Betriebswerte 1 HK2
    heating_circuit_2_switch_off_optimization:
      name: "HK2 Ausschaltoptimierung"
    heating_circuit_2_switch_on_optimization:
      name: "HK2 Einschaltoptimierung"
    heating_circuit_2_automatic:
      name: "HK2 Automatik"
    heating_circuit_2_ww_priority_processing:
      name: "HK2 Warmwasservorrang"
    heating_circuit_2_screed_drying:
      name: "HK2 Estrichtrocknung"
    heating_circuit_2_holiday:
      name: "HK2 Ferien"
    heating_circuit_2_antifreeze:
      name: "HK2 Frostschutz"
    heating_circuit_2_manually:
      name: "HK2 Manuell"
    # Betriebswerte 2 HK2
    heating_circuit_2_summer:
      name: "HK2 Sommer-Modus"
    heating_circuit_2_day:
      name: "HK2 Tag-Modus"
    heating_circuit_2_no_comm_with_rc:
      name: "HK2 Keine Kommunikation mit FB"
    heating_circuit_2_rc_faulty:
      name: "HK2 FB fehlerhaft"
    heating_circuit_2_flow_sensor_error:
      name: "HK2 Fehler Vorlauffuehler"
    heating_circuit_2_max_flow:
      name: "HK2 Maximaler Vorlauf"
    heating_circuit_2_external_fault_input:
      name: "HK2 Externer Stoereingang"

sensor:
  - platform: km271_wifi
    heating_circuit_2_flow_target_temperature:
      name: "HK2 Vorlaufsolltemperatur"
    heating_circuit_2_flow_temperature:
      name: "HK2 Vorlaufisttemperatur"
    heating_circuit_2_room_target_temperature:
      name: "HK2 Raumsolltemperatur"
    heating_circuit_2_room_temperature:
      name: "HK2 Raumisttemperatur"
    heating_circuit_2_pump_power:
      name: "HK2 Pumpenleistung"
    heating_circuit_2_mixer_position:
      name: "HK2 Mischerstellung"
    heating_circuit_2_curve_p10:
      name: "HK2 Heizkurve +10 °C"
    heating_circuit_2_curve_0:
      name: "HK2 Heizkurve 0 °C"
    heating_circuit_2_curve_n10:
      name: "HK2 Heizkurve -10 °C"

switch:
  - platform: gpio
    name: LED2_Green
    pin: 
      number: 22
      mode: OUTPUT
      inverted: true

text_sensor:
  - platform: km271_wifi
    firmware_version:
      name: "Firmware Version Control"